const InterestGroups = [
  {
    id: "iot",
    interestgroup: "Internet Of Things",
    interestgroupdescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas at ultricies nisl, eget finibus turpis. Donec pellentesque enim vel orci posuere, at scelerisque nulla vehicula. Fusce vulputate gravida consequat. Proin.",
    officetime: "Sunday 7:30",
    officeplace: "Discord Lobby",
    community: ["Fox Lab"],
    company: ["Thinkpalm"],
    mentors: [
      "Jaseel (Technical Program Manager - MakerGhat)",
      "Vijay Kumar M (CEO & MD - Webyfy Infotech Pvt Ltd)",
      "Sanju Mathew (Chief Executive Officer - Codeofduty)",
      "Akshai M (Embedded Software Engineer - STABL Energy GmbH)",
      "Samuel John (Co-Founder & CEO - mistEO)",
    ],
    learningpaths: [
      {
        name: "IOT Learning Path",
        link: "https://paths.tinkerhub.org/iot/",
      },
    ],
    basicenablementtasks: [
      {
        name: "IOT 101",
        link: "https://mulearn.atfg.gtechindia.org/page/iot101",
        complexity: "3",
        time: "40mins",
        karma: "200",
      },
      {
        name: "Getting Started with IoT Development - IBM Learning Path",
        link: "https://developer.ibm.com/learningpaths/iot-getting-started-iot-development/",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "Traffic Light Simulation",
        link: "https://docs.google.com/document/d/1_Z5CHJ6diesFpJJ_AwEQjqElB0U0GsIbmtt963HD1m4/edit?usp=drivesdk",
        complexity: "",
        time: "",
        karma: "",
      },
    ],
    corecourses: [
      {
        name: "28 Free IOT Courses You Can Take Right Now",
        link: "https://www.leverege.com/blogpost/28-free-iot-courses-you-can-take-right-now",
        complexity: "",
        time: "",
        karma: "400",
      },
    ],
    subcourses: [
      {
        name: "Python 3.4.3 Swayam Portal",
        link: "https://onlinecourses.swayam2.ac.in/aic20_sp33/",
        complexity: "",
        time: "",
        karma: "200",
      },
      {
        name: "Python for Beginners - Simplilear",
        link: "https://www.simplilearn.com/learn-python-basics-free-course-skillup",
        complexity: "",
        time: "",
        karma: "200",
      },
      {
        name: "Arduino Basics - Swayam Portal",
        link: "https://onlinecourses.swayam2.ac.in/aic20_sp04/",
        complexity: "",
        time: "",
        karma: "200",
      },
      {
        name: "Interface with Ardunio",
        link: "https://www.classcentral.com/course/interface-with-arduino-4325",
        complexity: "",
        time: "",
        karma: "200",
      },
    ],
  },
  {
    id: "uiux",
    interestgroup: "User Interface and Experience",
    interestgroupdescription:
      "Ever wondered how the vibrant apps and websites you see are designed? Wanna know how to? Join our interest group to learn with others who have common interest and get mentored by expert individuals.",
    officetime: "Sunday 7:30PM",
    officeplace: "Gathering Field",
    community: ["FoF Kochi", "GDSC MBCET"],
    company: ["Faya", "Experion Technologies"],
    mentors: [
      "Salman Faariz - GDSC MBCET",
      "Rhea Merin - GDSC MBCET",
      "Nauneet - GDSC MBCET",
    ],
    learningpaths: [
      {
        name: "User Experience Learning Path",
        link: "https://www.linkedin.com/learning/paths/become-a-user-experience-designer",
      },
      {
        name: "User Interface Learning Path",
        link: "https://brainstation.io/career-guides/how-to-become-a-ui-designer#:~:text=There%27s%20no%20single%20path%20to,design%20to%20coding%20to%20psychology.",
      },
    ],
    basicenablementtasks: [
      {
        name: "UI/UX",
        link: "https://mulearn.atfg.gtechindia.org/page/iot101",
        complexity: "3",
        time: "40 mins",
        karma: "100",
      },
      {
        name: "Create a Figma Account",
        link: "https://www.notion.so/mulearn/UI-UX-task-f21a97b9f7b042c3bfe7f5a2fa82bfbc",
        complexity: "1",
        time: "10 mins",
        karma: "200",
      },
      {
        name: "Create a UI for given wireframe",
        link: "https://www.notion.so/mulearn/UI-UX-Task-3-cab50a68b1714df79f691c7d5c099b63",
        complexity: "",
        time: "",
        karma: "",
      },
    ],
    corecourses: [
      {
        name: "My Great Learning Course",
        link: "https://olympus.mygreatlearning.com/courses/55928",
        complexity: "",
        time: "",
        karma: "400",
      },
    ],
    subcourses: [
      {
        name: "User Interface Design",
        link: "https://www.shortcoursesportal.com/studies/303816/user-interface-design.html?ref=search_card",
        complexity: "",
        time: "",
        karma: "200",
      },
    ],
  },
  {
    id: "web",
    interestgroup: "Web Development",
    interestgroupdescription:
      "Ever wondered how web and mobile applications are built? Everything seems greek until you get to how It is built.GTech μlearn's Web and Mobile Development Interest Group aims to develop and Fine-tune your Web, Mobile App Dev skills and bring together people who wish to evaluate potential Web and Mobile technologies. Join Now and Stay Updated!",
    officetime: "Saturday 7:30PM",
    officeplace: "Discord Lobby",
    community: ["Pygrammers"],
    company: ["Travancore Analytics", "PITS"],
    mentors: ["Shaheen Hyder - Pygrammers", "Shahanad - Pygrammers"],
    learningpaths: [
      {
        name: "Front End Learning Path",
        link: "https://roadmap.sh/frontend",
      },
      {
        name: "Back End Learning Path",
        link: "https://roadmap.sh/backend",
      },
      {
        name: "Complete Learning Path",
        link: "https://denic.hashnode.dev/you-want-to-learn-html-and-css-but-dont-know-where-to-get-started",
      },
    ],
    basicenablementtasks: [
      {
        name: "Create a Survey Form",
        link: "https://www.notion.so/mulearn/Survey-From-139baee23b1344cb82183c9495156e81",
        complexity: "3",
        time: "",
        karma: "200",
      },
      {
        name: "Recreate the given image using HTML CSS",
        link: "https://web.fe.up.pt/~arestivo/page/exercises/css/",
        complexity: "3",
        time: "30 mins",
        karma: "200",
      },
    ],
    corecourses: [
      {
        name: "HTML and CSS",
        link: "https://www.freecodecamp.org/learn/2022/responsive-web-design/",
        complexity: "3",
        time: "30mins",
        karma: "400",
      },
      {
        name: "Javascript Algorithms and DataStructre",
        link: "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/",
        complexity: "4",
        time: "",
        karma: "400",
      },
      {
        name: "Frontend Development Libraries",
        link: "https://www.freecodecamp.org/learn/front-end-development-libraries/",
        complexity: "4",
        time: "",
        karma: "400",
      },
      {
        name: "Backend Development and APIs",
        link: "https://www.freecodecamp.org/learn/back-end-development-and-apis/#back-end-development-and-apis-projects",
        complexity: "4",
        time: "",
        karma: "400",
      },
      {
        name: "Full Stack Development",
        link: "https://www.youtube.com/watch?v=EceJQ05KTf4&list=PLwoh6bBAszPrES-EOajos_E9gvRbL27wz",
        complexity: "5",
        time: "",
        karma: "400",
      },
    ],
    subcourses: [
      {
        name: "Git and Github",
        link: "https://www.classcentral.com/course/udacity-version-control-with-git-8430",
        complexity: "3",
        time: "",
        karma: "200",
      },
      {
        name: "Application Programming Interface(API)",
        link: "https://youtu.be/GZvSYJDk-us",
        complexity: "3",
        time: "",
        karma: "200",
      },
    ],
  },
  {
    id: "android",
    interestgroup: "Android Development",
    interestgroupdescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas at ultricies nisl, eget finibus turpis. Donec pellentesque enim vel orci posuere, at scelerisque nulla vehicula. Fusce vulputate gravida consequat. Proin.",
    officetime: "Saturday 7:30PM",
    officeplace: "Discord Lobby",
    community: ["Google"],
    company: ["Triassic Solutions", "PITS"],
    mentors: ["Vinu Balagopal"],
    learningpaths: [
      {
        name: "Kotlin",
        link: "https://kotlinlang.org/docs/home.html",
      },
      {
        name: "Architectures - MVP, MVC, MVVM",
        link: "https://www.oreilly.com/library/view/learning-javascript-design/9781449334840/ch10s09.html#:~:text=Both%20MVP%20and%20MVVM%20are,with%20the%20controller%20beside%20it.",
      },
      {
        name: "Android",
        link: "https://www.android.com/intl/en_in/",
      },
      {
        name: "Firebase",
        link: "https://firebase.google.com/docs",
      },
      {
        name: "Database",
        link: "https://www.javatpoint.com/what-is-database",
      },
    ],
    basicenablementtasks: [
      {
        name: "Android 101",
        link: "https://mulearn.atfg.gtechindia.org/page/android101",
        complexity: "4",
        time: "6 Hours",
        karma: "800",
      },
    ],
    corecourses: [
      {
        name: "Introduction to Kotlin",
        link: "https://www.youtube.com/watch?v=F9UC9DY-vIU",
        complexity: "",
        time: "",
        karma: "400",
      },
      {
        name: "Android Development Course",
        link: "https://www.youtube.com/watch?v=Iz08OTTjR04",
        complexity: "",
        time: "",
        karma: "400",
      },
    ],
    subcourses: [
      {
        name: "Git and Github",
        link: "https://www.classcentral.com/course/udacity-version-control-with-git-8430",
        complexity: "",
        time: "",
        karma: "200",
      },
      {
        name: "Application Programming Interface(API)",
        link: "https://youtu.be/GZvSYJDk-us",
        complexity: "",
        time: "",
        karma: "200",
      },
    ],
  },
  {
    id: "cybersec",
    interestgroup: "Cyber Security",
    interestgroupdescription:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas at ultricies nisl, eget finibus turpis. Donec pellentesque enim vel orci posuere, at scelerisque nulla vehicula. Fusce vulputate gravida consequat. Proin.",
    officetime: "Sunday 7:30PM",
    officeplace: "Discord Lobby",
    community: ["Beagle Security"],
    company: [],
    mentors: ["Rejah Rehim - Beagle Security", "Anees - Beagle Security"],
    learningpaths: [
      {
        name: "Cyber Security GTech Mulearn",
        link: "https://www.notion.so/lizchaitanya/Cybersecurity-uLearn-GTech-6ee1f80a98854de4b4774a80aa29a455",
      },
    ],
    basicenablementtasks: [
      {
        name: "Command Line",
        link: "https://www.youtube.com/watch?v=YHFzr-akOas",
        complexity: "3",
        time: "",
        karma: "",
      },
      {
        name: "Linux",
        link: "https://www.udemy.com/course/linux-basics-for-beginners/",
        complexity: "3",
        time: "",
        karma: "",
      },
      {
        name: "IT Funtamentals",
        link: "https://www.coursera.org/specializations/it-fundamentals-cybersecurity",
        complexity: "5",
        time: "",
        karma: "",
      },
    ],
    corecourses: [
      {
        name: "CISA-Certified Information Systems Auditor",
        link: "https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwjM7q_g-Jv6AhURAHIKHTtUAoEYABAAGgJzZg&ohost=www.google.com&cid=CAESbOD2dLEvktEhgQyG1ZDA_cdqkAbBW077r_DziQburAEx3yfVKc0AoFo5Odto3TWWb72G8qFUJjeL7LD0PDid16Ipm0S6A4HuHg5mYHvo8_5LkIYv2toHbYWxUHy3tNmu-UFKwh0kYJMME3zQeA&sig=AOD64_0Dk7n_LJn6kvprQR5ip4_Iws-oSg&q&adurl&ved=2ahUKEwi516jg-Jv6AhUt9zgGHZ93DSsQ0Qx6BAgGEAE",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "CCSP-Certified Cloud Security Professional",
        link: "https://www.udemy.com/course/ccsp-cloud-security-domain-1/",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "CISM-Certified Information Security Manager",
        link: "https://www.isaca.org/credentialing/cism?utm_source=google&utm_medium=cpc&utm_campaign=CertBAU&utm_content=sem_CertBAU_certification-cism-india-product-google&cid=sem_2006846&Appeal=sem&gclid=CjwKCAjw4JWZBhApEiwAtJUN0Mf5afTjnkDIauLbz5j_Dit01l4h1yfQgQ7tXi0CrEPsSiMy2HZUGRoCN9QQAvD_BwE",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "CIA-Certified Internal Auditor",
        link: "https://www.theiia.org/en/certifications/cia/",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "CEH-Certified Ethical Hacker",
        link: "https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/",
        complexity:
          "https://www.udemy.com/course/sql-injection-ethical-hacking/",
        time: "",
        karma: "",
      },
    ],
    subcourses: [
      {
        name: "SQL Injection",
        link: "",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "Social Engineering",
        link: "https://www.udemy.com/course/the-art-of-hacking-humans-intro-to-social-engineering/",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "Cryptography",
        link: "https://www.coursera.org/learn/crypto",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "Malware Threats",
        link: "https://www.udemy.com/topic/malware/",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "System Hacking",
        link: "https://www.udemy.com/topic/network-scanning/?utm_source=adwords&utm_medium=udemyads&utm_campaign=DSA_Catchall_la.EN_cc.INDIA&utm_content=deal4584&utm_term=_._ag_82569850245_._ad_533220805577_._kw__._de_c_._dm__._pl__._ti_dsa-506881825874_._li_9050518_._pd__._&matchtype=&gclid=CjwKCAjw4JWZBhApEiwAtJUN0KO6jcwgAWuN6hnTa0D-31GnuZ3KpialsbsICL9qDiCSVRRqykdHfRoCK-IQAvD_BwE",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "Footprinting and Reconnaissance",
        link: "https://www.cybrary.it/course/footprinting/",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "Scanning Networks",
        link: "https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwj0jIrB1Zv6AhUJJSsKHbx_DsMYABAAGgJzZg&ohost=www.google.com&cid=CAESbOD2hiFWisqDR74cmx-DlEiODflFGwt46suI16KrZauTeXgDPp2iAGA0R7qlfVnLwjK6r8YvRUn9BySTjkp7aD1sT3JFX854pt6uxu64rRcQwVgT-vxJ_IBC_jJ669WzXEOl0G_Fcs1YErhb3g&sig=AOD64_1kpAKmcVrHMwk5_HSNEyzlch6iDw&q&adurl&ved=2ahUKEwif_oPB1Zv6AhX1xTgGHdgMBgkQ0Qx6BAgDEAE",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "Enumeration",
        link: "https://www.udemy.com/course/enumeration-course-for-ethical-hackers/",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "Vulnerability Analysis",
        link: "https://www.udemy.com/course/vulnerability-analysis-course-for-ethical-hacking/",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "Sniffing",
        link: "https://www.cybrary.it/course/sniffing/",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "Denial-of-Service",
        link: "https://www.coursera.org/learn/ddos-attacks-and-defense",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "Session Hijacking",
        link: "https://www.cybrary.it/course/session-hijacking/",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "Hacking Web Servers",
        link: "https://www.udemy.com/course/hacking-web-applications-and-learn-penetration-testing/",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "Evading IDS, Firewalls, and Honeypots",
        link: "https://www.youtube.com/watch?v=IJlFPGLLTUU",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "Hacking Web Applications",
        link: "https://www.udemy.com/course/complete-web-application-hacking-penetration-testing/",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "Cloud Computing",
        link: "https://www.youtube.com/watch?v=2LaAJq1lB1Q",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "Hacking Wireless Networks",
        link: "https://www.mygreatlearning.com/academy/learn-for-free/courses/ethical-hacking-mobile-platforms-and-network-architecture",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "Hacking Mobile Platforms",
        link: "https://www.mygreatlearning.com/academy/learn-for-free/courses/ethical-hacking-mobile-platforms-and-network-architecture",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "Threat Intelligence",
        link: "https://www.coursera.org/learn/ibm-cyber-threat-intelligence",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "IoT and OT Hacking",
        link: "https://www.pluralsight.com/courses/hacking-iot-ot-ethical-hacking-ceh-cert",
        complexity: "",
        time: "",
        karma: "",
      },
    ],
  },
  {
    id: "pm",
    interestgroup: "Product Management",
    interestgroupdescription:
      '"Product Management is deciding what to build next”. Are you interested in learning to build the right product and the product right? Join our “Product Management” interest group to learn and collaborate with peers',
    officetime: "Sunday 8:00PM",
    officeplace: "Discord Lobby",
    community: ["Product Pack"],
    company: ["SunTec"],
    mentors: ["Nithin Balachandran", "Vineesh U S", "Aravind", "Savio"],
    learningpaths: [
      {
        name: "Ultimate Product Management Guide",
        link: "https://productschool.com/blog/product-management-2/ultimate-product-management-guide/",
      },
    ],
    basicenablementtasks: [
      {
        name: "Modern Product Management 101",
        link: "https://mulearn.acadle.com/courses/a3N1R2c5b3J3OHM1WVloNzE1Mg==/details",
        complexity: "3",
        time: "40 mins",
        karma: "100",
      },
      {
        name: "SWOT Analysis -Startbucks",
        link: "",
        complexity: "",
        time: "",
        karma: "",
      },
      {
        name: "For a food delivery app, what goals would you set for the next 6 months?",
        link: "",
        complexity: "",
        time: "",
        karma: "",
      },
    ],
    corecourses: [
      {
        name: "Product Management Course",
        link: "https://startinfinity.com/product-management-framework",
        complexity: "",
        time: "",
        karma: "400",
      },
    ],
    subcourses: [
      {
        name: "SWOT Analysis",
        link: "https://youtu.be/JXXHqM6RzZQ",
        complexity: "",
        time: "",
        karma: "200",
      },
      {
        name: "Business Analysis",
        link: "https://youtu.be/UBVzucVpG7k",
        complexity: "",
        time: "",
        karma: "200",
      },
    ],
    "": {},
  },
];

export default InterestGroups;
