const mentorListFaya = [
  {
    speakerID: "S1",
    name: "Sony John Bronzon",
    designation: "Heads Training and Development at ALLONTM.",
    stack: "Design Thinking",
    image: "https://www.fayaport80.com/speakers/thumb/Sony-John-Bronzon.jpg",
    linkedIn: "https://www.linkedin.com/in/sonyjohnbronzon/",
  },
  {
    speakerID: "S2",
    name: "Madhusudan Shekar",
    designation: "Chief Evangelist of Amazon Web Services, Amazon India",
    stack: "AWS Lambda",
    image: "https://www.fayaport80.com/speakers/thumb/Madhusudan-Shekar.jpg",
    linkedIn: "https://www.linkedin.com/in/madhusudanshekar/",
  },
  {
    speakerID: "S3",
    name: "Janeesh Uthuppan",
    designation:
      "digital marketing professional and the Founding Partner of Webdura Technologies",
    stack: "SEO",
    image: "https://www.fayaport80.com/speakers/thumb/Janeesh-Uthuppan.jpg",
    linkedIn: "https://www.linkedin.com/in/janeeshuthupp/",
  },
  {
    speakerID: "S4",
    name: "Rakesh B S",
    designation: "Co-Founders of Qucentis & BIGOrg",
    stack: "Blockchain",
    image: "https://www.fayaport80.com/speakers/thumb/Rakesh-B-S.jpg",
    linkedIn: "https://www.linkedin.com/in/rakesh-bs-78732817/",
  },
  {
    speakerID: "S5",
    name: "Jikku Jose",
    designation:
      "Ruby developer running a small startup by the name Qucentis in Kerala Startup Mission",
    stack: "Blockchain",
    image: "https://www.fayaport80.com/speakers/thumb/Jikku-Jose.jpg",
    linkedIn: "https://www.linkedin.com/in/jikkujose/",
  },
  {
    speakerID: "S6",
    name: "Krishnakumar S",
    designation:
      "Senior Consultant-Database Administration at EnvestNet Trivandrum",
    stack: "Database",
    image: "https://www.fayaport80.com/speakers/thumb/Krishnakumar-S.jpg",
    linkedIn: "https://www.linkedin.com/in/krishnakumars1/",
  },
  {
    speakerID: "S7",
    name: "Jeswin Simon",
    designation: "Senior Engineer - Product, Envestnet",
    stack: "Swift 4",
    image: "https://www.fayaport80.com/speakers/thumb/Jeswin-Simon.jpg",
    linkedIn: "http://in.linkedin.com/pub/jeswin-simon/20/405/184",
  },
  {
    speakerID: "S8",
    name: "Jaydev S V",
    designation: "Founder of volvox",
    stack: "Singularity Series",
    image: "https://www.fayaport80.com/speakers/thumb/Jaydev-S-V.jpg",
    linkedIn: "",
  },
  {
    speakerID: "S9",
    name: "Hrishi Olickel",
    designation: "Founder of volvox",
    stack: "Singularity Series",
    image: "https://www.fayaport80.com/speakers/thumb/Hrishi-Olickel.jpg",
    linkedIn: "https://www.linkedin.com/in/hrishioa/",
  },
  {
    speakerID: "S10",
    name: "Manuyash Chaudhary",
    designation: "AI & NLP Developer & Researcher, Accubits Technologies",
    stack: "Deep Learning",
    image: "https://www.fayaport80.com/speakers/thumb/manuyash-chaudhary.jpg",
    linkedIn: "",
  },
  {
    speakerID: "S11",
    name: "Suchit Majumdar",
    designation: "Chief Data Science Evangelist, UpX Academy, Hyderabad",
    stack: "Artificial Intelligence",
    image: "https://www.fayaport80.com/speakers/thumb/Suchit-Majumdar.jpg",
    linkedIn: "https://www.linkedin.com/in/suchitmajumdar/",
  },
  {
    speakerID: "S12",
    name: "Amal Dev",
    designation: "Technical Analyst, UST Global",
    stack: "Docker",
    image: "https://www.fayaport80.com/speakers/thumb/Amal-Dev.jpg",
    linkedIn: "https://www.linkedin.com/in/amaldevv/",
  },
  {
    speakerID: "S13",
    name: "Shine Xavier",
    designation: "Senior Architect, UST Global",
    stack: "JavaScript",
    image: "https://www.fayaport80.com/speakers/thumb/Shine-Xavier.jpg",
    linkedIn: "https://www.linkedin.com/in/shinexavier/",
  },
  {
    speakerID: "S14",
    name: "Amal Shehu",
    designation: "JS Frontend Engineers, FAYA Innovations",
    stack: "Angular 4",
    image: "https://www.fayaport80.com/speakers/thumb/Amal-Shehu.jpg",
    linkedIn: "https://www.linkedin.com/in/amal-shehu-639824104/",
  },
  {
    speakerID: "S15",
    name: "Vijay Kumar M",
    designation: "CEO & MD – Webyfy Infotech Pvt Ltd",
    stack: "IOT",
    image: "https://www.fayaport80.com/speakers/thumb/Vijay-Kumar-M.jpg",
    linkedIn: "https://www.linkedin.com/in/vijay-kumar-m-04818b/",
  },
  {
    speakerID: "S16",
    name: "Anand Ramkumar",
    designation: "Senior Test Engineer, Experion Technologies, Trivandrum",
    stack: "AWS farm",
    image: "https://www.fayaport80.com/speakers/thumb/Anand-Ramkumar.jpg",
    linkedIn: "",
  },
  {
    speakerID: "S17",
    name: "Sarath Varma Asokan",
    designation: "Senior Consultant (Software Testing), Se-Mentor, Trivandrum.",
    stack: "",
    image: "https://www.fayaport80.com/speakers/thumb/Sarath-Varma-Asokan.jpg",
    linkedIn: "https://www.linkedin.com/in/sarath-varma-88441811/",
  },
  {
    speakerID: "S18",
    name: "Praseed Pai",
    designation: "software architect working in UST Global",
    stack: "Blockchain",
    image: "https://www.fayaport80.com/speakers/thumb/Praseed-Pai.jpg",
    linkedIn: "https://www.linkedin.com/in/praseed-pai-k-t-369ba225/",
  },
  {
    speakerID: "S19",
    name: "Deepak Varma",
    designation: "Director, Technospirit Consulting, Cochin",
    stack: "Big Data",
    image: "https://www.fayaport80.com/speakers/thumb/Deepak-Varma.jpg",
    linkedIn: "https://www.linkedin.com/in/deepak-varma/",
  },
  {
    speakerID: "S20",
    name: "Nikhil Krishna",
    designation: "Solutions Architect working in UST Global",
    stack: "Kubernetes",
    image: "https://www.fayaport80.com/speakers/thumb/Nikhil-Krishna.jpg",
    linkedIn: "https://www.linkedin.com/in/nikhilkrishna/",
  },
  {
    speakerID: "S21",
    name: "Sarath C",
    designation: "Architect at Experion Technologies, Technopark, Trivandrum",
    stack: "fastlane tools,Swift",
    image: "https://www.fayaport80.com/speakers/thumb/Sarath-C.jpg",
    linkedIn: "https://www.linkedin.com/in/sarathc/",
  },
  {
    speakerID: "S22",
    name: "Priya Sivakumar",
    designation: "Delivery Head, TATA Elxsi",
    stack: "DevOps",
    image: "https://www.fayaport80.com/speakers/thumb/Priya-Sivakumar.jpg",
    linkedIn: "",
  },
  {
    speakerID: "S23",
    name: "Vijay Dev",
    designation: "Lead Front-End Developer of Qburst",
    stack: "React.js",
    image: "https://www.fayaport80.com/speakers/thumb/Vijay-Dev.jpg",
    linkedIn: "https://www.linkedin.com/in/vijaydev/",
  },
  {
    speakerID: "S24",
    name: "Nikhil Raj R",
    designation: "Senior SEO Engineer at Alamy Images India Pvt.Ltd.",
    stack: "SEO",
    image: "https://www.fayaport80.com/speakers/thumb/Nikhil-Raj-R.jpg",
    linkedIn: "https://www.linkedin.com/in/nikhilrajr/",
  },
  {
    speakerID: "S25",
    name: "Aneesh Sreedharan",
    designation:
      "Chief Exicutive & Technology Enthusiast, 2Hats Logic Solutions, Kochi",
    stack: "Magento 2",
    image: "https://www.fayaport80.com/speakers/thumb/Aneesh-Sreedharan.jpg",
    linkedIn: "https://www.linkedin.com/in/aneeshsreedharan/",
  },
  {
    speakerID: "S26",
    name: "Liju Pillai",
    designation: "Co-founder & CEO of Perfomatix Solutions Pvt Ltd",
    stack: "Angular JS",
    image: "https://www.fayaport80.com/speakers/thumb/Liju-Pillai.jpg",
    linkedIn: "https://www.linkedin.com/in/lijurajpillai/",
  },
  {
    speakerID: "S27",
    name: "Ashik Ajith",
    designation: "Software Engineer, Ruby Software India Pvt.Ltd.",
    stack: "Ruby",
    image: "https://www.fayaport80.com/speakers/thumb/Ashik-Ajith.jpg",
    linkedIn: "https://www.linkedin.com/in/ashikajith/",
  },
  {
    speakerID: "S28",
    name: "Rajeev J Sebastian",
    designation: "CEO, Alokin Software",
    stack: "Python",
    image: "https://www.fayaport80.com/speakers/thumb/Rajeev-J-Sebastian.jpg",
    linkedIn: "https://www.linkedin.com/in/rajeev-j-sebastian-290b972/",
  },
  {
    speakerID: "S29",
    name: "Faiz Mohamed Haneef",
    designation: "Director - Neoito Technologies Pvt Ltd",
    stack: "Angular",
    image: "https://www.fayaport80.com/speakers/thumb/Faiz-Mohamed-Haneef.jpg",
    linkedIn: "https://www.linkedin.com/in/faizmh/",
  },
  {
    speakerID: "S30",
    name: "Deepu S Nath",
    designation: "Managing Director - Tech Faya Innovations Pvt Ltd",
    stack: " JavaScript,Angular",
    image: "https://www.fayaport80.com/speakers/thumb/Deepu-S-Nath.jpg",
    linkedIn: "https://www.linkedin.com/in/deepusnath/",
  },
  {
    speakerID: "S31",
    name: "Nithin S",
    designation: "",
    stack: "JavaScript",
    image: "https://www.fayaport80.com/speakers/thumb/Nithin-S.jpg",
    linkedIn: "https://www.linkedin.com/in/nithins/",
  },
  {
    speakerID: "S32",
    name: "Shiraz Samad",
    designation: "Front End Developer at DBG",
    stack: "JavaScript",
    image: "https://www.fayaport80.com/speakers/thumb/Shiraz-Samad.jpg",
    linkedIn: "https://www.linkedin.com/in/shirazsamad/",
  },
  {
    speakerID: "S33",
    name: "Lakshmikant Deshpande",
    designation: "Neoito Technologies",
    stack: "Angular",
    image:
      "https://www.fayaport80.com/speakers/thumb/Lakshmikant-Deshpande.jpg",
    linkedIn: "https://www.linkedin.com/in/lakshmikant-deshpane/",
  },
  {
    speakerID: "S34",
    name: "Mohana Kumar",
    designation: "Senior Software Developer",
    stack: "Big Data Analytics",
    image: "https://www.fayaport80.com/speakers/thumb/Mohana-Kumar.jpg",
    linkedIn: "",
  },
  {
    speakerID: "S35",
    name: "Aromal Sasidharan",
    designation: "IOS developer at DBG",
    stack: "Switch",
    image: "https://www.fayaport80.com/speakers/thumb/Aromal-Sasidharan.jpg",
    linkedIn: "https://www.linkedin.com/in/aromal-sasidharan-870b4032/",
  },
  {
    speakerID: "S36",
    name: "Thahir Maheen",
    designation: "IOS developer at DBG",
    stack: "Swift",
    image: "https://www.fayaport80.com/speakers/thumb/Thahir-Maheen.jpg",
    linkedIn: "https://www.linkedin.com/in/thahir-maheen-554b9548/",
  },
  {
    speakerID: "S37",
    name: "Adarsh V C",
    designation: "IOS developer(Team Lead) at DBG",
    stack: "MBaaS",
    image: "https://www.fayaport80.com/speakers/thumb/Adarsh-V-C.jpg",
    linkedIn: "https://www.linkedin.com/in/adarshvc/",
  },
  {
    speakerID: "S38",
    name: "Praveen Vijayan",
    designation: "Front-end developer at Flip Media",
    stack: "Web App Developers",
    image: "https://www.fayaport80.com/speakers/thumb/Praveen-Vijayan.jpg",
    linkedIn: "https://www.linkedin.com/in/pvnair/",
  },
  {
    speakerID: "S39",
    name: "Dr. Jayaraj Poroor",
    designation: "Founder of DependSoft Consulting",
    stack: "Node.JS Express",
    image: "https://www.fayaport80.com/speakers/thumb/Dr-Jayaraj-Poroor.jpg",
    linkedIn: "https://www.linkedin.com/in/jayarajporoor/",
  },
  {
    speakerID: "S40",
    name: "Shameer B",
    designation: "UI Lead at FAYA",
    stack: "HTML5 & CSS",
    image: "https://www.fayaport80.com/speakers/thumb/Shameer-B.jpg",
    linkedIn: "https://www.linkedin.com/in/shameerbadarudeen/",
  },
  {
    speakerID: "S41",
    name: "Rahul Raj",
    designation: "UX Lead at FAYA",
    stack: "Mastering HTML5 & CSS3",
    image: "https://www.fayaport80.com/speakers/thumb/Rahul-Raj.jpg",
    linkedIn: "https://www.linkedin.com/in/rahul-raj-sr-15a42030/",
  },
  {
    speakerID: "S42",
    name: "Sumil K S",
    designation: "UI Developer at FAYA",
    stack: "Mastering HTML5 & CSS3",
    image: "https://www.fayaport80.com/speakers/thumb/Sumil-K-S.jpg",
    linkedIn: "https://www.linkedin.com/in/sumilks/",
  },
  {
    speakerID: "S43",
    name: "Ganesh Kumar G",
    designation: "Senior UI Developer at McFadyen Digital",
    stack: "",
    image: "https://www.fayaport80.com/speakers/thumb/Ganesh-Kumar-G.jpg",
    linkedIn: "https://www.linkedin.com/in/ganeshkumargopinathan/",
  },
  {
    speakerID: "S44",
    name: "Haneefa T P",
    designation: "Developer at FAYA",
    stack: "Angular JS,Knockout JS",
    image: "https://www.fayaport80.com/speakers/thumb/Haneefa-T-P.jpg",
    linkedIn: "https://www.linkedin.com/in/haneefa/",
  },
  {
    speakerID: "S45",
    name: "Sreenath Sasikumar",
    designation: "Developer at FAYA",
    stack: "Angular JS,Knockout JS",
    image: "https://www.fayaport80.com/speakers/thumb/Sreenath-Sasikumar.jpg",
    linkedIn: "https://www.linkedin.com/in/sreenathsasikumar/",
  },
  {
    speakerID: "S46",
    name: "Suresh Babu",
    designation: "Firmusoft Pvt. Ltd",
    stack: "Angular JS,Knockout JS",
    image: "https://www.fayaport80.com/speakers/thumb/Suresh-Babu.jpg",
    linkedIn: "https://www.linkedin.com/in/suresh-babu-9b764a18/",
  },
  {
    speakerID: "S47",
    name: "Rejah Rehim",
    designation: "FAYA",
    stack: "Jenkins",
    image: "https://www.fayaport80.com/speakers/thumb/Rejah-Rehim.jpg",
    linkedIn: "https://www.linkedin.com/in/rejah/",
  },
  {
    speakerID: "S48",
    name: "Rahul Krishnan",
    designation: "Attinad Software",
    stack: "",
    image: "https://www.fayaport80.com/speakers/thumb/Rahul-Krishnan.jpg",
    linkedIn: "https://www.linkedin.com/in/rahulkrish/",
  },
  {
    speakerID: "S49",
    name: "Sudhahar Viswanathan",
    designation: "QA Lead at FAYA",
    stack: "",
    image: "https://www.fayaport80.com/speakers/thumb/Sudhahar-Viswanathan.jpg",
    linkedIn: "https://www.linkedin.com/in/sudhaharv/",
  },
  {
    speakerID: "S50",
    name: "Sajin T M",
    designation: "FAYA",
    stack: "Apache Solr",
    image: "https://www.fayaport80.com/speakers/thumb/Sajin-TM.jpg",
    linkedIn: "https://www.linkedin.com/in/sajin-tm-23223612/",
  },
  {
    speakerID: "S51",
    name: "Madhav M Nair",
    designation: "Sr Developer for VR-AR Tech at UST Global",
    stack: "AR / VR / MR / CR",
    image: "https://www.fayaport80.com/speakers/thumb/Madhav-M-Nair.jpg",
    linkedIn: "https://www.linkedin.com/in/madhavmnair/",
  },
  {
    speakerID: "S52",
    name: "Savio Victor",
    designation:
      "AI enthusiast and entrepreneur, co-founder of air.ai and KnightClan.",
    stack: "Artificial Intelligence",
    image: "https://www.fayaport80.com/speakers/thumb/Savio-Victor.jpg",
    linkedIn: "https://www.linkedin.com/in/saviovictor/",
  },
  {
    speakerID: "S53",
    name: "Viju Chacko",
    designation: "Senior Consultant at Tata Consultancy Services ",
    stack: "Artificial Intelligence",
    image: "https://www.fayaport80.com/speakers/thumb/Viju-Chacko.jpg",
    linkedIn: "https://www.linkedin.com/in/vijuchacko/",
  },
  {
    speakerID: "S54",
    name: "Charles Andrews",
    designation: "Singularity evangelist and entrepreneur",
    stack: "Singularity Series",
    image: "https://www.fayaport80.com/speakers/thumb/Charles-Andrews.jpg",
    linkedIn: "",
  },
  {
    speakerID: "S55",
    name: "Amarnath Sankar",
    designation: "CEO at CAT Entertainments Pvt Ltd & Co-Founder at TastySpots",
    stack: "Crowdfunding",
    image: "https://www.fayaport80.com/speakers/thumb/Amarnath-Sankar.jpg",
    linkedIn: "https://www.linkedin.com/in/amarnath-sankar-142a59a/",
  },
  {
    speakerID: "S56",
    name: "Abdul Muhyami Arif",
    designation: "Mobile developer at FantaCode",
    stack: "Xamarin",
    image: "https://www.fayaport80.com/speakers/thumb/Abdul-Muhyami-Arif.jpg",
    linkedIn: "https://www.linkedin.com/in/muhaym/",
  },
  {
    speakerID: "S57",
    name: "Pranoy Radhakrishnan",
    designation: "Deep Learning researcher and co-founder of air.ai",
    stack: "Artificial Intelligence",
    image: "https://www.fayaport80.com/speakers/thumb/Pranoy-Radhakrishnan.jpg",
    linkedIn: "https://www.linkedin.com/in/pranoy-radhakrishnan-63846888/",
  },
  {
    speakerID: "S58",
    name: "Michael Gord",
    designation: "Founder & CEO, MLG Blockchain Consulting",
    stack: "",
    image: "https://www.fayaport80.com/speakers/thumb/Michael-Gord.jpg",
    linkedIn: "https://www.linkedin.com/in/mgord/",
  },
  {
    speakerID: "S59",
    name: "Satish Babu",
    designation: "Chair, APRALO - ICANN",
    stack: "FOSS",
    image: "https://www.fayaport80.com/speakers/thumb/satish-babu.jpg",
    linkedIn: "https://www.linkedin.com/in/sierrabravo/",
  },
  {
    speakerID: "S60",
    name: "Venkatramanan P R",
    designation: "Data Scientist, Thought Works",
    stack: "Machine Learning Systems",
    image: "https://www.fayaport80.com/speakers/thumb/Venkatramanan.jpg",
    linkedIn: "https://www.linkedin.com/in/venkatramanan-p-r-a25b0321/",
  },
  {
    speakerID: "S61",
    name: "Professor Nandini Vaidyanathan",
    designation: "Chairman and M D, CARMa Venture Services",
    stack: "",
    image: "https://www.fayaport80.com/speakers/thumb/nandini.jpg",
    linkedIn: "https://www.linkedin.com/in/nandinivaidyanathan/",
  },
  {
    speakerID: "S62",
    name: "Rama Brahmam Aleti",
    designation: "Co-Founder & UX Strategist, Think Design Collaborative",
    stack: "UX",
    image: "https://www.fayaport80.com/speakers/thumb/rama-brahmam.jpg",
    linkedIn: "https://www.linkedin.com/in/aleti-rama-brahmam-127a835/",
  },
  {
    speakerID: "S63",
    name: "Sanju Mathew",
    designation: "CEO, Onbyz",
    stack: "Smarter Wearables",
    image: "https://www.fayaport80.com/speakers/thumb/sanju-mathew.jpg",
    linkedIn: "https://www.linkedin.com/in/sanjumathewk/",
  },
  {
    speakerID: "S64",
    name: "Abhilash Ashok",
    designation: "Senior Lead, UX Development, Valorem",
    stack: "VR, AR & MR",
    image: "https://www.fayaport80.com/speakers/thumb/abhilash-ashok.jpg",
    linkedIn: "https://www.linkedin.com/in/abhilashca/",
  },
  {
    speakerID: "S65",
    name: "Anivar Aravind",
    designation: "Founder Executive Director, Indic Project",
    stack: "Civic Technologies",
    image: "https://www.fayaport80.com/speakers/thumb/anivar.jpg",
    linkedIn: "https://www.linkedin.com/in/anivar/",
  },
  {
    speakerID: "S66",
    name: "Mohammed Rafi T F",
    designation:
      "Behavioural Scientist, Life Transformation Specialist and International Master Trainer, Neuro Lingusitic Programme",
    stack: "Phantoms in the Brain",
    image: "https://www.fayaport80.com/speakers/thumb/rafi.jpg",
    linkedIn: "",
  },
  {
    speakerID: "S67",
    name: "M Sivasankar IAS",
    designation: "IT Secretary, Government of Kerala",
    stack: "",
    image: "https://www.fayaport80.com/speakers/thumb/sivasankar.jpg",
    linkedIn: "",
  },
  {
    speakerID: "S68",
    name: "Dr. Asharaf S",
    designation: "Associate Professor, IIITMK",
    stack: "",
    image: "https://www.fayaport80.com/speakers/thumb/ashraf.jpg",
    linkedIn: "https://www.linkedin.com/in/asharafs/",
  },
  {
    speakerID: "S69",
    name: "Rahul Alex Panicker",
    designation: "Co-founder & President, Embrace Innovations",
    stack: "",
    image: "https://www.fayaport80.com/speakers/thumb/rahul-alex.jpg",
    linkedIn: "https://www.linkedin.com/in/rahulap/",
  },
  {
    speakerID: "S70",
    name: "Anoop Ambika",
    designation: "Founder, CLAP Research",
    stack: "",
    image: "https://www.fayaport80.com/speakers/thumb/anoop.jpg",
    linkedIn: "https://www.linkedin.com/in/anoopambika/?ppe=1",
  },
  {
    speakerID: "S71",
    name: "Pinaki Krishna Pillai",
    designation: "Founder, Microm CRM",
    stack: "Digital Marketing",
    image:
      "https://www.fayaport80.com/speakers/thumb/Pinaki-Krishna-Pillai.jpg",
    linkedIn: "https://www.linkedin.com/in/pinakipillai/",
  },
  {
    speakerID: "S72",
    name: "Dilip Mathew Thomas",
    designation: "Independent Consultant- Deep Learning",
    stack: "Deep Learning",
    image: "https://www.fayaport80.com/speakers/thumb/Dilip-Mathew-Thomas.jpg",
    linkedIn: "https://www.linkedin.com/in/dilip-thomas-83b355a0/",
  },
  {
    speakerID: "S73",
    name: "Sreeraj S",
    designation: "Chief Architect of Servntire Global",
    stack: " Ethereum and DAPPs.",
    image: "https://www.fayaport80.com/speakers/thumb/Sreeraj-S.jpg",
    linkedIn: "https://www.linkedin.com/in/sreeraj-s/",
  },
  {
    speakerID: "S74",
    name: "Sarath Soman",
    designation: "Software Engineer at Hifx",
    stack: "Java Virtual Machine 101",
    image: "https://www.fayaport80.com/speakers/thumb/Sarath-Soman.jpg",
    linkedIn: "https://www.linkedin.com/in/sarath-soman-3a3aa564/",
  },
  {
    speakerID: "S75",
    name: "Mahroof K",
    designation: "Cedex Technologies LLP",
    stack: "chatbots",
    image: "https://www.fayaport80.com/speakers/thumb/Mahroof-K.jpg",
    linkedIn: "https://www.linkedin.com/in/mahroofk/",
  },
  {
    speakerID: "S76",
    name: "Jubin Jose",
    designation: "Cedex Technologies LLP",
    stack: "Chatbot Development",
    image: "https://www.fayaport80.com/speakers/thumb/Jubin-Jose.jpg",
    linkedIn: "https://www.linkedin.com/in/jubin-jose-cet/",
  },
  {
    speakerID: "S77",
    name: "Gopikrishnan V",
    designation: "Founder, BuildNext",
    stack: "VR",
    image: "https://www.fayaport80.com/speakers/thumb/Gopikrishnan-V.jpg",
    linkedIn: "https://www.linkedin.com/in/gopikrishnanv/",
  },
  {
    speakerID: "S78",
    name: "Manu Krishnan",
    designation: "Co-founder of DayScholars Innovations Pvt. Ltd",
    stack: "Laravel",
    image: "https://www.fayaport80.com/speakers/thumb/Manu-Krishnan.jpg",
    linkedIn: "https://www.linkedin.com/in/tvmanukrishnan/",
  },
  {
    speakerID: "S79",
    name: "Abhiram A",
    designation: "Unity3D Ambassador, Unity India",
    stack: "AR,VR,MR",
    image: "https://www.fayaport80.com/speakers/thumb/Abhiram-A.jpg",
    linkedIn: "https://www.linkedin.com/in/abhir6m/",
  },
  {
    speakerID: "S80",
    name: "Alex Devassy",
    designation: "Senior Blockchain Engineer at Serventire Global",
    stack: "Blockchain",
    image: "https://www.fayaport80.com/speakers/thumb/Alex-Devassy.jpg",
    linkedIn: "https://www.linkedin.com/in/alex-devassy-358421138/",
  },
  {
    speakerID: "S81",
    name: "Fariz Rahman",
    designation: "Deep Learning Engineer, Skymind",
    stack: "Keras",
    image: "https://www.fayaport80.com/speakers/thumb/Fariz-Rahman.jpg",
    linkedIn: "https://www.linkedin.com/in/fariz-rahman-2b20443a/",
  },
  {
    speakerID: "S82",
    name: "Hari S. Pillai",
    designation: "Technical Lead at Perfomatix",
    stack: "Angular 6",
    image: "https://www.fayaport80.com/speakers/thumb/Hari-s-pillai.jpeg",
    linkedIn: "",
  },
  {
    speakerID: "S82",
    name: "Rejin Narayanan",
    designation: "founder, Ingen Robotics.",
    stack: "Robotics",
    image: "https://www.fayaport80.com/speakers/thumb/Rejin-Narayanan.jpg",
    linkedIn: "https://www.linkedin.com/in/rejin/",
  },
  {
    speakerID: "S83",
    name: "Ajith Kumar M",
    designation: "Robotics Developer at TCS-ILP Innovations Lab",
    stack: "Robot operating system",
    image: "https://www.fayaport80.com/speakers/thumb/Ajith-kumar.jpg",
    linkedIn: "",
  },
  {
    speakerID: "S84",
    name: "Sanu George",
    designation: "Senior consultant for Usability engineering at IBS",
    stack: "UX",
    image: "https://www.fayaport80.com/speakers/thumb/Sanu-George.jpg",
    linkedIn: "https://www.linkedin.com/in/sanugeorge-ux/",
  },
  {
    speakerID: "S85",
    name: "Ajith V Giri",
    designation: "Mobile App Developer working at SoftFrit Solutions",
    stack: "Firebase",
    image: "https://www.fayaport80.com/speakers/thumb/Ajith-V-Giri.jpg",
    linkedIn: "",
  },
  {
    speakerID: "S86",
    name: "Noufal Ibrahim",
    designation: "Founder and Director of Hamon Technologies, LLP, Kozhikode",
    stack: " Data Structures with Python",
    image: "https://www.fayaport80.com/speakers/thumb/Noufal-ibrahim.jpg",
    linkedIn: "https://in.linkedin.com/in/noufalibrahim",
  },
  {
    speakerID: "S87",
    name: "Renjith Raj",
    designation: "Chief Technical Officer at SayOne Technologies",
    stack: "Flutter",
    image: "https://www.fayaport80.com/speakers/thumb/Renjith-raj.jpg",
    linkedIn: "https://www.linkedin.com/in/renjithraj2005/",
  },
  {
    speakerID: "S88",
    name: "Ravi Padmaraj",
    designation: "Architect at QBurst Technologies",
    stack: "Spark and Scala",
    image: "https://www.fayaport80.com/speakers/thumb/Ravi-Padmaraj.jpeg",
    linkedIn: "",
  },
  {
    speakerID: "S89",
    name: "Jobin C S",
    designation: "Co-Founder & CEO of Tenderwoods",
    stack: "Cordova",
    image: "https://www.fayaport80.com/speakers/thumb/Jobin-CS.jpg",
    linkedIn: "https://www.linkedin.com/in/jobin-c-s-26b5b56a/",
  },
  {
    speakerID: "S90",
    name: "Paul Emil Johnson",
    designation: "Founder – AwesomeDaddies Interactive",
    stack: "Product Development",
    image: "https://www.fayaport80.com/speakers/thumb/Paul-emil-johnson.jpg",
    linkedIn: "https://www.linkedin.com/in/paulemiljohnson/",
  },
  {
    speakerID: "S91",
    name: "Roel Vlemmings",
    designation:
      "Founding Partner and the Chief Product Officer at RedBlack Software",
    stack: "Scrum",
    image: "https://www.fayaport80.com/speakers/thumb/Roel-Vlemmings.jpg",
    linkedIn: "https://www.linkedin.com/in/rvlemmings/",
  },
  {
    speakerID: "S92",
    name: "Suresh Balasubramanian",
    designation: "Co-founder & CEO at ExpressBase Systems",
    stack: "Rapid application Development",
    image:
      "https://www.fayaport80.com/speakers/thumb/Suresh-balasubramanian.jpg",
    linkedIn: "https://www.linkedin.com/in/sureba73/",
  },
  {
    speakerID: "S93",
    name: "Afsal Muttikkal",
    designation: "Automation Head at Genrobotic Innovations",
    stack: "Mechatronics",
    image: "https://www.fayaport80.com/speakers/thumb/Afsal.jpg",
    linkedIn: "https://www.linkedin.com/in/afsalmuttikkal/",
  },
  {
    speakerID: "S94",
    name: "GeorgeKutty George",
    designation: "CEO, Lookings Soft.<br>Mentor, Reacthub",
    stack: "React Native",
    image: "https://www.fayaport80.com/speakers/thumb/georgekutty-george.jpg",
    linkedIn: "https://www.linkedin.com/in/georgekutty-george-a558a788/",
  },
  {
    speakerID: "S95",
    name: "Simsarul Haq Vengasseri",
    designation: "Quantum Computing Researcher, Infinity Labs, UST",
    stack: "Quantum Computing",
    image: "https://www.fayaport80.com/speakers/thumb/simsar.jpg",
    linkedIn: "https://www.linkedin.com/in/simsarul-haq-vengasseri-65a2b8a3/",
  },
  {
    speakerID: "S96",
    name: "Sabeer Sulaiman",
    designation: "Technical lead, Fantacode",
    stack: " Angular 7",
    image: "https://www.fayaport80.com/speakers/thumb/sabeer.jpg",
    linkedIn: "https://www.linkedin.com/in/sabeersulaiman/",
  },
  {
    speakerID: "S97",
    name: "Mahroof Ali",
    designation: "Founder, Tensorbot Innovations",
    stack: "IOT",
    image: "https://www.fayaport80.com/speakers/thumb/mahroof-ali.jpg",
    linkedIn: "https://www.linkedin.com/in/mahroof-ali-1991a9137/",
  },
  {
    speakerID: "S98",
    name: "Nirmal Vyas",
    designation:
      "Web designer and developer<br>Consultant, passionate coder and name",
    stack: "Vue.Js",
    image: "https://www.fayaport80.com/speakers/thumb/nirmal-vyas.jpg",
    linkedIn: "",
  },
  {
    speakerID: "S99",
    name: "Rijin Ramesh",
    designation:
      "Co-founder and head of product and technology, Articbot Pvt Ltd",
    stack: "Chatbot",
    image: "https://www.fayaport80.com/speakers/thumb/rijin_ramesh.jpg",
    linkedIn: "https://www.linkedin.com/in/rijin-ramesh-31809375/",
  },
  {
    speakerID: "S100",
    name: "Ashik Salman",
    designation: "Co-founder at Ecart.chat",
    stack: "Ruby",
    image: "https://www.fayaport80.com/speakers/thumb/",
    linkedIn: "https://www.linkedin.com/in/ashik-salman-a487a596/",
  },
  {
    speakerID: "S101",
    name: "Asif Mohammed",
    designation: "JS Frontend Engineer, FAYA Innovations",
    stack: "JavaScript",
    image: "https://www.fayaport80.com/speakers/thumb/asif_mohammed.jpg",
    linkedIn: "https://www.linkedin.com/in/asif-mohammed-18b2bb150/",
  },
  {
    speakerID: "S102",
    name: "Deepu Xavier",
    designation: "Co-founder, ZappyHire",
    stack: "Product Management",
    image: "https://www.fayaport80.com/speakers/thumb/Deepu_xavier.jpg",
    linkedIn: "https://www.linkedin.com/in/deepu-xavier-8b126330/",
  },
  {
    speakerID: "S103",
    name: "Sreelakshmy P",
    designation: "Assistant Manager at Deloitte India",
    stack: "Cyber Security",
    image: "https://www.fayaport80.com/speakers/thumb/Sreelakshmy.jpg",
    linkedIn: "https://www.linkedin.com/in/sreelakshmy-p/",
  },
  {
    speakerID: "S104",
    name: "Karthik Kalathil",
    designation:
      "CTO and Co-founder at Wattlecorp | Security Consultant | Cybersecurity Product Innovation Manager | name",
    stack: "cyber security",
    image: "https://www.fayaport80.com/speakers/thumb/Karthik-kalathil.jpg",
    linkedIn: "https://www.linkedin.com/in/kalathil-karthik/",
  },
  {
    speakerID: "S105",
    name: "Srinivas P",
    designation: "Centre Head @ Alamy India",
    stack: "project / program management",
    image: "https://www.fayaport80.com/speakers/thumb/Srinivas-p.jpg",
    linkedIn: "https://www.linkedin.com/in/srinivas-paladugu-2a68b53/",
  },
  {
    speakerID: "S106",
    name: "Suresh Kumar M",
    designation: "Sr. Principal Manager – Product Development @ Alamy India",
    stack: "Product Development",
    image: "https://www.fayaport80.com/speakers/thumb/suresh-kumar.jpg",
    linkedIn:
      "https://www.linkedin.com/in/suresh-kumar-madhavan-pillai-a027b51a/",
  },
  {
    speakerID: "S107",
    name: "Jeswin S George",
    designation: "Quality Assurance Engineer, Qburst Technologies",
    stack: "",
    image: "https://www.fayaport80.com/speakers/thumb/jeswin.jpg",
    linkedIn: "https://www.linkedin.com/in/jeswin-s-george-a6489192/",
  },
  {
    speakerID: "S108",
    name: "Cipson Thomas",
    designation: "Agile & Kanban Coach, Trainer & Consultant",
    stack: "Agile software development",
    image: "https://www.fayaport80.com/speakers/thumb/cipson.jpg",
    linkedIn: "https://www.linkedin.com/in/cipson/",
  },
  {
    speakerID: "S109",
    name: "Sijil Salim",
    designation: "Lead Engineer, IBS",
    stack: "automation and voice based technologies",
    image: "https://www.fayaport80.com/speakers/thumb/sijil.jpg",
    linkedIn: "https://www.linkedin.com/in/sijil-s-3b90b440/",
  },
  {
    speakerID: "S110",
    name: "Akshai M",
    designation: "Senior Research Fellow, ICFOSS",
    stack: "Embedded Device Engineering",
    image: "https://www.fayaport80.com/speakers/thumb/akshai.jpg",
    linkedIn: "https://www.linkedin.com/in/akshaim/",
  },
  {
    speakerID: "S111",
    name: "Hari Shankar R",
    designation: "Technical Support Engineer, Automattic",
    stack: "web development",
    image: "https://www.fayaport80.com/speakers/thumb/harishanker.jpg",
    linkedIn: "https://www.linkedin.com/in/harishanker/",
  },
  {
    speakerID: "S112",
    name: "Jubin Jose",
    designation: "Senior NLP engineer, Cedex Technologies",
    stack: "machine learning",
    image: "https://www.fayaport80.com/speakers/thumb/jubin.jpg",
    linkedIn: "https://www.linkedin.com/in/jubin-jose-dev/",
  },
  {
    speakerID: "S113",
    name: "Amar C.P",
    designation:
      "Co-founder & CTO , VinamSolutions Pvt Ltd & Luvia Global Marketing Agency",
    stack:
      "Object Oriented Programming(OOP), Symfony Framework, Linux, PHP7, MySQL, Elasticsearch",
    image: "https://www.fayaport80.com/speakers/thumb/amar.jpg",
    linkedIn: "https://www.linkedin.com/in/amarcp/",
  },
  {
    speakerID: "S114",
    name: "Biju K Nair",
    designation:
      "Independent Lawyer, Consultant with Open Invention Network and License on Transfer Network",
    stack: "",
    image: "https://www.fayaport80.com/speakers/thumb/biju.jpg",
    linkedIn: "https://www.linkedin.com/in/biju-k-nair-0499468/",
  },
  {
    speakerID: "S115",
    name: "Arun Sasi",
    designation: "Joomla Template developer & Lead designer, IBS Software",
    stack: "Joomla Template Development",
    image: "https://www.fayaport80.com/speakers/thumb/arun-sasi.jpg",
    linkedIn: "https://www.linkedin.com/in/arunayr/",
  },
  {
    speakerID: "S116",
    name: "Samuel",
    designation: "Cofounder of MistEO",
    stack: "",
    image: "https://www.fayaport80.com/speakers/thumb/samuel.jpg",
    linkedIn: "",
  },
  {
    speakerID: "S117",
    name: "Liji Thomas",
    designation: "Technical Manager, Valorem Reply",
    stack: "",
    image: "https://www.fayaport80.com/speakers/thumb/liji-thomas.jpg",
    linkedIn: "https://www.linkedin.com/in/liji-thomas/",
  },
  {
    speakerID: "S118",
    name: "Shahul E S",
    designation: "Co-founder at alrt.ai",
    stack:
      "Data Analytics, Data Science, Machine learning, Deep learning, and Natural language processing",
    image: "https://www.fayaport80.com/speakers/thumb/shahul.jpg",
    linkedIn: "https://www.linkedin.com/in/shahules/",
  },
  {
    speakerID: "S119",
    name: "Vinesh S",
    designation: "Senior Frontend Engineer, QBurst",
    stack: "JavaScript",
    image: "https://www.fayaport80.com/speakers/thumb/vinesh.jpg",
    linkedIn: "https://www.linkedin.com/in/s-vinesh-10139572/",
  },
  {
    speakerID: "S120",
    name: "Robin Tommy",
    designation: "Incubation Lab Head, Tata Consultancy Services",
    stack: "Startup",
    image: "https://www.fayaport80.com/speakers/thumb/Robin-Tommy.jpg",
    linkedIn: "https://www.linkedin.com/in/robintommy/",
  },
  {
    speakerID: "S121",
    name: "Vinod Narayan",
    designation:
      "Agile Coach | SAFe® SPC | Educator, Founder, Penpositive Inc.",
    stack: "Agile software development",
    image: "https://www.fayaport80.com/speakers/thumb/Vinod-Narayan.jpg",
    linkedIn: "https://www.linkedin.com/in/vinodn/",
  },
  {
    speakerID: "S122",
    name: "Amrit Sanjeev",
    designation:
      "Staff Developer Advocate at Google and leads the developer advocacy initiatives for India.",
    stack: "Android",
    image: "https://www.fayaport80.com/speakers/thumb/amrit-sanjee.jpg",
    linkedIn:
      "https://www.linkedin.com/search/results/all/?keywords=Amrit%20Sanjeev&origin=GLOBAL_SEARCH_HEADER",
  },
  {
    speakerID: "S123",
    name: "Mandar Patil ",
    designation:
      "Senior Solutions Architecture at Amazon Internet Services Private Limited.",
    stack: "Product Development, Dev Ops",
    image: "https://www.fayaport80.com/speakers/thumb/mandar-patil.jpg",
    linkedIn: "",
  },
  {
    speakerID: "S124",
    name: "Nikhil Chandran",
    designation: "Founder & Ceo - Tiltlabs ",
    stack: "Metaverse, Web 3.0",
    image: "https://www.fayaport80.com/speakers/thumb/Nikhil_Chandran.jpg",
    linkedIn: "https://www.linkedin.com/in/nikhil-tiltlabs/",
  },
  {
    speakerID: "S125",
    name: "Joel Zachariah",
    designation: "Creative Director - Tiltlabs ",
    stack: "",
    image: "https://www.fayaport80.com/speakers/thumb/Joel-Zachariah.jpg",
    linkedIn: "https://www.linkedin.com/in/joel-zachariah-531b1a11a/",
  },
  {
    speakerID: "S126",
    name: "Melvin Thambi",
    designation: "Artist | Designer & Creative Entrepreneur from Texas",
    stack: "product design, NFT",
    image: "https://www.fayaport80.com/speakers/thumb/melvin_thambi.jpg",
    linkedIn: "https://www.linkedin.com/in/melvinthambi/",
  },
  {
    speakerID: "S127",
    name: "Anantha Krishnan Nadamel",
    designation: "NFT Artist | Visual Designer UXD at TCS Interactive",
    stack: "Digital art",
    image:
      "https://www.fayaport80.com/speakers/thumb/Anantha-Krishnan-Nadamel.jpg",
    linkedIn:
      "https://www.linkedin.com/in/anantha-krishnan-s-kurup-301134176/?originalSubdomain=in",
  },
  {
    speakerID: "S128",
    name: "Adeeb Abdul Salam",
    designation: "Computer Engineer from IITD | Blockchain Researcher",
    stack: "Blockchain",
    image: "https://www.fayaport80.com/speakers/thumb/Adeeb-Abdul-Salam.jpg",
    linkedIn:
      "https://www.linkedin.com/in/zeroknowledgep/?originalSubdomain=qa",
  },
  {
    speakerID: "S129",
    name: "Dr. Koshy P. Vaidyan",
    designation: "CEO, TrEST Research Park",
    stack:
      "Business Architecture, Business Process Transformation, Business/IT Strategy",
    image: "https://www.fayaport80.com/speakers/thumb/Koshy-P-Vaidyan.jpg",
    linkedIn:
      "https://www.linkedin.com/in/dr-koshy-p-vaidyan-9868aa29/?originalSubdomain=in",
  },
  {
    speakerID: "S130",
    name: "Gautam S.T.",
    designation: "Director, Gyanoholic International Pvt. Ltd.",
    stack:
      "Robotics, Electronics, Programming, 3D printing, Automobile Engineering",
    image: "https://www.fayaport80.com/speakers/thumb/Gautam-S-T.jpg",
    linkedIn: "https://www.linkedin.com/in/gautamst/?originalSubdomain=in",
  },
];

export default mentorListFaya;
