const mainlink = "https://mulearn.org"
export const links = [
  {
    head: -1,
    name: "About",
    submenu: true,
    sublinks: [
      {
        name: "The Team",
        submenu: true,
        sublinks: [
          {
            name: "Our Team",
            submenu: false,
            sublinks: [],
            link: mainlink + "/team",
            foreign: false,
          },
        ],
      },
      {
        name: "Partners",
        submenu: true,
        sublinks: [
          {
            name: "Community Partners",
            submenu: false,
            sublinks: [],
            link: mainlink + "/community-partners",
            foreign: false,
          },
          {
            name: "Company Partners",
            submenu: false,
            sublinks: [],
            link: mainlink + "/company-partners",
            foreign: false,
          },
        ],
      },
      {
        name: "Participate",
        submenu: true,
        sublinks: [
          {
            name: "Enablers & Mentor",
            submenu: false,
            sublinks: [],
            link: mainlink + "/participate",
            foreign: false,
          },
        ],
      },
      {
        name: "Leaderboard",
        submenu: true,
        sublinks: [
          {
            name: "Overall Leaderboards",
            link: mainlink + "/leaderboard",
          },
          {
            name: "Monthly Leaderboards",
            link: mainlink + "/leaderboard/monthly",
          },
        ],
      },
      {
        name: "Media",
        submenu: true,
        sublinks: [
          {
            name: "Gallery",
            submenu: false,
            sublinks: [],
            link: mainlink + "/gallery",
            foreign: false,
          },
          {
            name: "News",
            submenu: false,
            sublinks: [],
            link: mainlink + "/news",
            foreign: false,
          },
          {
            name: "Blogs",
            submenu: false,
            sublinks: [],
            link: mainlink + "/blogs",
            foreign: false,
          },
        ],
      },
      {
        name: "Campus Chapters",
        submenu: true,
        sublinks: [
          {
            name: "Home Page",
            submenu: false,
            sublinks: [],
            link: mainlink + "/campuschapters",
            foreign: false,
          },
          {
            name: "Success Stories",
            submenu: false,
            sublinks: [],
            link: mainlink + "/blogs",
            foreign: false,
          },
        ],
      },
    ],
  },
  {
    head: -1,
    name: "Programs",
    submenu: true,
    sublinks: [
      {
        head: 1,
        name: "Flagship",
        submenu: true,
        sublinks: [
          {
            name: "YIP 2021",
            submenu: false,
            sublinks: [],
            link: mainlink + "/yip",
            foreign: false,
          },
          {
            name: "Foundation Program",
            submenu: false,
            sublinks: [],
            link: "https://foundation.mulearn.org",
            foreign: true,
          },
          {
            name: "Art of Teaching",
            submenu: false,
            sublinks: [],
            link: mainlink + "/artofteaching",
            foreign: false,
          },
        ],
      },
      {
        head: 1,
        name: "Ongoing",
        submenu: true,
        sublinks: [
          {
            name: "Bootcamps",
            submenu: false,
            sublinks: [],
            link: "/bootcamps",
            foreign: false,
          },
        ],
      },
      {
        head: 1,
        name: "Others",
        submenu: true,
        sublinks: [
          {
            name: "Wiki Syllabus",
            submenu: false,
            sublinks: [],
            link: mainlink + "/wikisyllabus",
            foreign: false,
          },
          {
            name: "Hacktober Fest",
            submenu: false,
            sublinks: [],
            link: mainlink + "/hacktoberfest",
            foreign: false,
          },
          {
            name: "Build For Team",
            submenu: false,
            sublinks: [],
            link: mainlink + "/BuildForTeam",
            foreign: false,
          },
        ],
      },
    ],
  },
  {
    head: -1,
    name: "Events Page",
    submenu: true,
    sublinks: [
      {
        head: 2,
        name: "Global Calendar",
        submenu: true,
        sublinks: [
          {
            name: "Calendar",
            link: mainlink + "/calendar",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
        ],
      },
      {
        head: 2,
        name: "Announcements",
        submenu: true,
        sublinks: [
          {
            name: "Announcements",
            link: mainlink + "/announcements",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
        ],
      },
      {
        head: 2,
        name: "Weekly Events",
        submenu: true,
        sublinks: [
          {
            name: "Home",
            link: mainlink + "/events",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "Inspiration Station",
            link: mainlink + "/isr",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "Mentor Connect",
            link: mainlink + "/events/mentorconnect",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "Open Mic",
            link: mainlink + "/events/openmic",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "Salt Mango Tree",
            link: mainlink + "/events/saltmangotree",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
        ],
      },
    ],
  },
  {
    head: -1,
    name: "Interest Group",
    submenu: true,
    sublinks: [
      {
        head: 3,
        name: "Interest Groups",
        submenu: true,
        sublinks: [
          {
            name: "Home",
            link: "/",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "Android Development",
            link: "/android",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "Artifical Intelligence",
            link: "/ai",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "Cyber Security",
            link: "/cybersec",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "IoT",
            link: "/iot",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "Product Management",
            link: "/pm",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "UI / UX",
            link: "/uiux",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "Web Development",
            link: "/web",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
        ],
      },
      {
        head: 3,
        name: "Bootcamps",
        submenu: true,
        sublinks: [
          {
            name: "Home",
            link: "/bootcamps",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "Android",
            link: "/bootcamps/android",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "Artificial Intelligence",
            link: "/bootcamps/ai",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "CTF",
            link: "/bootcamps/ctf",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "Flutter",
            link: "/bootcamps/flutter",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "Rust",
            link: "/bootcamps/rust",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "JavaScript",
            link: "/bootcamps/javascript",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "Python",
            link: "/bootcamps/python",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
        ],
      },
      {
        head: 3,
        name: "Practice",
        submenu: true,
        sublinks: [
          {
            name: "OpenSource Projects",
            link: "/opensource",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "Problem Shelf",
            link: "/problemshelves",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "Challenges",
            link: "/challenges",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "Courses",
            link: "/courses",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "API Setu",
            link: "/apisetu",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
        ],
      },
      {
        head: 3,
        name: "Learning Circles",
        submenu: true,
        sublinks: [
          {
            name: "Create Circle",
            link: "/create",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "Join Circles",
            link: "/join",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
        ],
      },
      {
        head: 3,
        name: "Search",
        submenu: true,
        sublinks: [
          {
            name: "Mentor Directory",
            link: "/mentors",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
          {
            name: "Existing Circles",
            link: "/searchcircles",
            submenu: false,
            sublinks: [],
            foreign: false,
          },
        ],
      },
    ],
  },
]
