const data = [
        {
            name: "Event 1545454a44a45",
            date: "01-01-2023",
            logo_url: "httpxxxxs://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Instagram_logo_2022.svg/768px-Instagram_logo_2022.svg.png",
            projects: [
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                        desc: "",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8aHVtYW58ZW58MHx8MHx8&w=1000&q=80",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
            ]
        },
        {
            name: "Event 2",
            date: "01-01-2023",
            logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Instagram_logo_2022.svg/768px-Instagram_logo_2022.svg.png",
            projects: [
                {
                    title: "Project x",
                    members: ["Rabik", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project y",
                    members: ["Fiza", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project z",
                    members: ["Ruby", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
            ]
        },
        {
            name: "Event 1",
            date: "01-01-2023",
            logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Instagram_logo_2022.svg/768px-Instagram_logo_2022.svg.png",
            projects: [
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
            ]
        },
        {
            name: "Event 1",
            date: "01-01-2023",
            logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Instagram_logo_2022.svg/768px-Instagram_logo_2022.svg.png",
            projects: [
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
            ]
        },
        {
            name: "Event 1",
            date: "01-01-2023",
            logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Instagram_logo_2022.svg/768px-Instagram_logo_2022.svg.png",
            projects: [
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
            ]
        },
        {
            name: "Event 1",
            date: "01-01-2023",
            logo_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Instagram_logo_2022.svg/768px-Instagram_logo_2022.svg.png",
            projects: [
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 1",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "3Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 3",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "2Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
                {
                    title: "Project 4",
                    members: ["Alice", "Bob", "Charlie"],
                    gitlink: "https://github.com/project1",
                    sitelink: "https://project1.com",
                    img_link: "https://project1.com/images/logo.png",
                    desc: "1Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                },
            ]
        }
    ]   
export default data